---
title: "STM"
author: "Jonathon Sun"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STM

```{r STM}
# Page 7 instructions https://cran.r-project.org/web/packages/stm/vignettes/stmVignette.pdf

processed <- textProcessor(Philly_Education_Long$location_name, metadata = Philly_Education_Long)
out <- prepDocuments(processed$documents, processed$vocab, processed$meta)
docs <- out$documents
vocab <- out$vocab
meta <- out$meta

#Page 8
plotRemoved(processed$documents, lower.thresh = seq(1, 200, by = 100)) #Clears infrequent words
out <- prepDocuments(processed$documents, processed$vocab, processed$meta, lower.thresh = 15)

#Page 9
poliblogPrevFit <- stm(documents = out$documents, 
                       vocab = out$vocab, 
                       K = 20, 
                       max.em.its = 75, 
                       data = out$meta, 
                       init.type = "Spectral")

poliblogSelect <- selectModel(out$documents, out$vocab, K = 20, 
                              max.em.its = 75, 
                              data = out$meta, 
                              runs = 20, 
                              seed = 8458159)

plotModels(poliblogSelect, pch=c(1,2,3,4), legend.position="bottomright")

storage <- searchK(out$documents, 
                   out$vocab, 
                   K = c(7, 10),
                   data = meta)


```
